### Add a New Course
POST http://localhost:5000/courses
Content-Type: application/json

{
  "department": "CSI",
  "number": 101,
  "title": "Introduction to Computer Science",
  "description": "An introductory course to computer science.",
  "credits": 3
}

### Get Prerequisites for a Course
GET http://localhost:5000/course_prerequisites/21

### Get course concentration
http://localhost:5000/course_concentrations/CSI/1/concentration

### Get course by concentration
http://localhost:5000/course_concentrations/Artificial%20Intelligence%20and%20Machine%20Learning

### Progress test
POST http://localhost:5000/progress/completed_progress
Content-Type: application/json

{
  "courses": [
    { "course_id": 21, "credits": 3, "grade": "A" },
    { "course_id": 25, "credits": 3, "grade": "B+" },
    { "course_id": 5, "credits": 3, "grade": "A-" },
    { "course_id": 23, "credits": 3, "grade": "B" },
    { "course_id": 4, "credits": 3, "grade": "C+" },
    { "course_id": 11, "credits": 4, "grade": "B-" },
    { "course_id": 27, "credits": 3, "grade": "B-" }
  ],
  "selectedConcentration": "Artificial Intelligence and Machine Learning"
}

### course description
POST http://localhost:5000/courses/description
Content-Type: application/json

{
  "course_id": 9999
}

### Progress test
POST http://localhost:5000/progress/completed_progress
Content-Type: application/json

{
  "courses": [
    { "course_id": 21, "credits": 3, "grade": "A" },
    { "course_id": 25, "credits": 3, "grade": "B+" },
    { "course_id": 5, "credits": 3, "grade": "A-" },
    { "course_id": 23, "credits": 3, "grade": "B" },
    { "course_id": 4, "credits": 3, "grade": "C+" },
    { "course_id": 11, "credits": 4, "grade": "B-" },
    { "course_id": 27, "credits": 3, "grade": "B-" }
  ],
  "selectedConcentration": "Signal Processing and Communications"
}





### Progress test
POST http://localhost:5000/progress/completed_progress
Content-Type: application/json
[{     id: 1, year: '2023',semester: 'Fall', department: 'CSI',    number: '500',title: 'Operating Systems (3)',grade: 'A',     credits: 3,     user_id: null,     completed: 'yes'   } ]
